ld.lld: fix definition of ebda_segment
The GNU linker and the LLVM linker don't agree on handling changes to
the location counter within a section. Consider the following example:

  SECTIONS {
    .section_foo 0x1000 (NOLOAD) : {
      . = 0x1000;
      symbol = .;
    }

Linker behavior:
- GNU LD:  symbol = 0x2000
- LLVM LD: symbol = 0x1000

We unify this behavior by increasing the location counter rather than
setting it:

  SECTION {
    .section_foo 0x1000 (NOLOAD) : {
      . += 0x1000;
      symbol = .;
  }

This sets symbol = 0x2000 with both linkers.

Change-Id: Ib59f074a68c63f2ef6e820e59789c6046d5bf5f0